### ISSUE TITLE
eForms SDK 1.11.0

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#204]
https://github.com/OP-TED/eForms-SDK/releases/tag/1.11.0

1.10 was https://github.com/open-contracting/european-union-support/issues/196

## Relevant

New fields

- OPT-093-Review
- BT-1501(s)-Contract (mandatory) replaced by BT-1501(c)-Contract (mandatory) and BT-1501(p)-Contract (optional). The guidance had been:

```yaml
     eForms guidance: Discard. The notice and sections that were modified can be determined by comparing previous releases with the current release.
     eForms example: <efac:ContractModification><efac:Change><efbc:ChangedSectionIdentifier>CON-0001</efbc:ChangedSectionIdentifier></efac:Change></efac:ContractModification>
     OCDS example: ''
     sdk: https://docs.ted.europa.eu/eforms/latest/schema/contract-modification-notice.html
```

Now using country instead of eforms-country codelist. Our guidance has a special case for Kosovo. It looks like it's no longer needed.

- BT-191-Tender
- BT-514-Organization-Company
- BT-514-Organization-TouchPoint
- BT-514-UBO
- BT-5141-Lot
- BT-5141-Part
- BT-5141-Procedure
- BT-706-UBO

## Maybe relevant

Now optional

- BT-115-Part
- BT-22-Lot
- BT-22-LotsGroup
- BT-660-LotResult
- BT-709-LotResult
- OPT-301-Lot-EmployLegis
- OPT-301-Lot-EnvironLegis
- OPT-301-Lot-FiscalLegis
- OPT-301-Part-EmployLegis
- OPT-301-Part-EnvironLegis
- OPT-301-Part-FiscalLegis

Now mandatory

- BT-119-LotResult
- BT-120-Lot
- BT-193-Tender
- BT-31-Procedure
- BT-33-Procedure
- BT-40-Lot
- BT-50-Lot
- BT-51-Lot
- BT-52-Lot
- BT-553-Tender
- BT-555-Tender
- BT-57-Lot
- BT-635-LotResult
- BT-64-Lot
- BT-661-Lot
- BT-710-LotResult
- BT-712(b)-LotResult
- BT-729-Lot
- BT-730-Tender
- BT-731-Tender
- BT-732-Lot
- BT-75-Lot
- BT-7531-Lot
- BT-7532-Lot
- BT-755-Lot
- BT-759-LotResult
- BT-76-Lot
- BT-760-LotResult
- BT-772-Lot
- BT-777-Lot
- BT-98-Lot
- BT-99-Lot
- OPT-030-Procedure-SProvider
- OPT-070-Lot
- OPT-111-Lot-FiscalLegis
- OPT-111-Part-FiscalLegis
- OPT-112-Lot-EnvironLegis
- OPT-112-Part-EnvironLegis
- OPT-113-Lot-EmployLegis
- OPT-113-Part-EmployLegis
- OPT-170-Tenderer
- OPT-210-Tenderer
- OPT-300-Tenderer
- OPT-301-Lot-ReviewInfo

## Not relevant

Changed `pattern` validation

- BT-1252-Procedure new pattern: was UUID
- BT-13716-notice: more prefixes (discarded)
